/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "Console.h"
#include "NRF24L01.h"



NRF24L01_Config master1;

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(USART1, 9600);

	NRF24L01_Reset(&master1);

	master1.Interrupt_Enable = false;
	master1.Address_Length = NRF24L01_Address_Length.Byte_5;
	master1.CRC_type = NRF24L01_CRC.ONE_BYTE;
	master1.RF_Power       = NRF24L01_Power.PWR_0dBm;
	master1.Data_Rate = NRF24L01_Data_Rate._2MBPS;
	master1.RF_Channel = NRF24L01_RF_Channel.Speed_2Mbps.CH_MHz_2404;
	NRF24L01_Init(&master1);















    /* Loop forever */
	for(;;);
}
