/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "Console.h"
#include "NRF24L01.h"

NRF24L01_Config master1;
NRF24L01_Config master2;

SPI_Config master_slave1;
SPI_Config master_slave2;

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(USART1, 9600);

	SPI_Config_Reset(&master_slave1);
	SPI_Config_Reset(&master_slave2);


	master1.NRF24L01_SPI_Driver = master_slave1;
	master2.NRF24L01_SPI_Driver = master_slave2;



	NRF24L01_Init(&master1);
	NRF24L01_Init(&master2);




    /* Loop forever */
	for(;;);
}
